Add a card without component
devetek/Terpusat-Frontend pull request #46
Opened 2020-11-16 05:10 UTC by Alwiaulian

2020-11-17 12:51 UTC, prakasa-tkpd requested changes
yang bagian down menu di cardnya bisa di ganti ke link detail pagenya aja. Untuk sekarang. link ke dummy page aja dulu, mungkin tokopedia.com/terpusat.

![image](https://user-images.githubusercontent.com/48669953/99392701-b2bddb80-290e-11eb-9531-8445ee2e867c.png)



btw sama 1 lg, kalo bikin commit minta tolong yang agak deskriptif :D ... Biar enak di tracing:
![image](https://user-images.githubusercontent.com/48669953/99392799-e26ce380-290e-11eb-96ce-e4c9d0e4aff5.png)


kalo mau commit lakuin ini aja `git commit` . Otomatis bakal ada command prompt yang minta lu isi/nyeritain tentang changes lu melakukan apa.

2020-11-19 11:54 UTC, Alwiaulian commented
> yang bagian down menu di cardnya bisa di ganti ke link detail pagenya aja. Untuk sekarang. link ke dummy page aja dulu, mungkin tokopedia.com/terpusat.
> 
> ![image](https://user-images.githubusercontent.com/48669953/99392701-b2bddb80-290e-11eb-9531-8445ee2e867c.png)
> 
> btw sama 1 lg, kalo bikin commit minta tolong yang agak deskriptif :D ... Biar enak di tracing:
> ![image](https://user-images.githubusercontent.com/48669953/99392799-e26ce380-290e-11eb-96ce-e4c9d0e4aff5.png)
> 
> kalo mau commit lakuin ini aja `git commit` . Otomatis bakal ada command prompt yang minta lu isi/nyeritain tentang changes lu melakukan apa.

2020-11-19 11:54 UTC, closed without merging

2020-11-19 11:55 UTC, Alwiaulian commented
Yang bagian down better delete aja aapa gmana? soalnya di description yg tulisan warna merah udah ada link

2020-11-19 12:31 UTC, prakasa-tkpd commented
> Yang bagian down better delete aja aapa gmana? soalnya di description yg tulisan warna merah udah ada link

Sebenernya keliatan bagus sih, tp kalo dihide dlu gpp keknya. Biar cepet selesai dulu aja yg bagian penting2nya